apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.yaml: |
    server:
      port: 8080
    database:
      host: mysql
      port: 3306
    redis:
      host: redis
      port: 6379
