apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-http-service
  template:
    metadata:
      labels:
        app: go-http-service
    spec:
      containers:
      - name: app
        image: go-http-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
