apiVersion: v1
kind: Service
metadata:
  name: go-http-service
  labels:
    app: go-http-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-http-service
