openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /mymethod:
    get:
      summary: My Method
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string