mysql:
  host: "localhost"
  port: 3306
  user: "your_mysql_user"
  password: "your_mysql_password"
  database: "your_database_name"

redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password"

openai:
  api_key: "your_openai_api_key"